### ISSUE TITLE
Rework wallet page

### ISSUE THREAD

**Issue by treeder** [gochain-io/explorer#440]
The idea is to make it simpler and more usable. Right now it takes many clicks to get the point of sending a transaction when it could all just be one simple form. Also, forcing user to enter private key first makes it annoying when you want to enter the to and amount before entering the private key. 

#### Phase 1
* [x] Drop 'owned tokens' tab (can already find on address page)
* [x] Drop 'transactions' tab (can already find on address page)
* [ ] Drop 'use contract' tab (can already interact from contract page)
* [x] Make hex address a link to address page

#### Phase 2
* [ ] Drop all tabs
* [ ] Show one single form with everything in it to send or deploy a contract
* [ ] After private key is entered, show balance near the field (can enter PK at any time) - metamask will show balance in the metamask popup so we probably don't need to show it for MM. But if we can show it easily, then let's do that.

**Comment by jmank88** [comment]
I reorganized things in to two parts. Phase 1 can be added pretty easily to #430 now. After that, we could merge and do phase 2 separately (which requires more reworking of the UI layout). @brockmcblockchain could you post the latest mock-up for the desired form layout?

**Comment by brockmcblockchain** [comment]
Rough Mocks from our previous chats.

![Screen Shot 2019-10-30 at 10 41 32 AM](https://user-images.githubusercontent.com/39677511/68785685-8e009b00-060c-11ea-813d-de1344cd36aa.jpg)
![Screen Shot 2019-10-30 at 10 27 43 AM](https://user-images.githubusercontent.com/39677511/68785691-8fca5e80-060c-11ea-8aed-34a4b1098e8d.jpg)

**Comment by treeder** [comment]
Wonder if it would be useful to save the private key in session storage (until they close the tab) so they can browse around, use contracts, use the wallet, etc. until they are done?  Or too insecure?
